"""Trace: add meta_data

Revision ID: e17f7dd0f7b1
Revises: e2f1ac919e1a
Create Date: 2020-05-14 15:15:41.558188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e17f7dd0f7b1'
down_revision = 'e2f1ac919e1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trace', sa.Column('contact', sa.Unicode(length=255), nullable=True))
    op.add_column('trace', sa.Column('contact_mail', sa.Unicode(length=255), nullable=True))
    op.add_column('trace', sa.Column('description', sa.UnicodeText(), nullable=True))
    op.add_column('trace', sa.Column('title', sa.Unicode(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trace', 'title')
    op.drop_column('trace', 'description')
    op.drop_column('trace', 'contact_mail')
    op.drop_column('trace', 'contact')
    # ### end Alembic commands ###
