"""Trace

Revision ID: e2f1ac919e1a
Revises: 
Create Date: 2020-05-14 12:46:45.077829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2f1ac919e1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=8), nullable=True),
    sa.Column('root_client', sa.Integer(), nullable=True),
    sa.Column('root_location', sa.Integer(), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('stop', sa.DateTime(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['root_client'], ['client.id'], ),
    sa.ForeignKeyConstraint(['root_location'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('direct_trace_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['trace_id'], ['trace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indirect_trace_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['trace_id'], ['trace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indirect_trace_client')
    op.drop_table('direct_trace_client')
    op.drop_table('trace')
    # ### end Alembic commands ###
